import React from "react";
import Head from "next/head";

type Props = {
    title: string;
}

const Meta = (props: Props) => {
    return(
        <Head>
          <title>{`${props.title} | 静岡大学 ITソルーション室`}</title>
          <meta name = "description" content = "静岡大学学生団体であるITソルーション室のホームページです。"/>
          <meta name="viewport" content="initial-scale=1, width=device-width" />
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default Meta;